name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Revisar el repositorio"
        uses: actions/checkout@v3

      - name: "Instalar Node.js"
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: "Instalar dependencias"
        run: npm install

      - name: "Ejecutar script"
        run: node script.js
        env:
          DATA_BASE_STRING: ${{ secrets.DATA_BASE_STRING }}
          VALOR_UNO_SECRET: ${{ secrets.VALOR_UNO_SECRET }}
          VALOR_DOS_SECRET: ${{ secrets.VALOR_DOS_SECRET }}
