name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Revisar el repositorio"
        uses: actions/checkout@v3

      # Imprimir un mensaje de prueba
      - name: "Mostrar mensaje"
        run: echo "Hola mundo"

      # Imprimir variables de entorno definidas en GitHub Secrets
      - name: "Mostrar variables de entorno"
        run: |
          echo "Imprimiendo variables de entorno..."
          echo "DATA_BASE_STRING: ${{ secrets.DATA_BASE_STRING }}"
          echo "VALOR_UNO_SECRET: ${{ secrets.VALOR_UNO_SECRET }}"
          echo "VALOR_DOS_SECRET: ${{ secrets.VALOR_DOS_SECRET }}"
