name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Revisar el repositorio"
        uses: actions/checkout@v3

      - name: "Mostrar mensaje"
        run: echo "Hola mundo"

      # Mostrar variables de entorno definidas como secretos y variables
      - name: "Mostrar variables de entorno y secretos"
        run: |
          echo "Imprimiendo variables de entorno y secretos..."
          echo "DATA_BASE_STRING: ${{ secrets.DATA_BASE_STRING }}"
          echo "VALOR_UNO_SECRET: ${{ secrets.VALOR_UNO_SECRET }}"
          echo "VALOR_DOS_SECRET: ${{ secrets.VALOR_DOS_SECRET }}"
          echo "PORT: $PORT"          # Imprimir la variable de entorno PORT
          echo "VALOR_UNO: $VALOR_UNO" # Imprimir la variable de entorno VALOR_UNO
          echo "VALOR_DOS: $VALOR_DOS" # Imprimir la variable de entorno VALOR_DOS
